[project]
name = "weather_api_server"
version = "1.0"
description = "WeatherMe Application"
dependencies = [
    "flask"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"